# Generated by Django 4.0.4 on 2022-05-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='chemistry_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='cs_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='physics_marks',
            field=models.IntegerField(null=True),
        ),
    ]
