# Generated by Django 4.0.4 on 2022-05-27 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_form_chemistry_marks_form_cs_marks_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='form',
            new_name='register',
        ),
    ]
