# Generated by Django 4.0.4 on 2022-05-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_rename_form_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='perentage',
            field=models.IntegerField(null=True),
        ),
    ]
