# Generated by Django 4.0.4 on 2022-05-27 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_register_perentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='perentage',
            new_name='percentage',
        ),
    ]
