# Generated by Django 4.0.4 on 2022-05-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_rename_perentage_register_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='percentage',
        ),
        migrations.AddField(
            model_name='register',
            name='per',
            field=models.FloatField(null=True),
        ),
    ]
